select * from customers

-- Ques1 -> what is the total revenue generated by male and female customers?

select gender , sum(purchase_amount) as revenue
from customers
group by 1;

-- Ques2 -> which customer used a discount but still purchased than the average purchase amount?
select customer_id , purchase_amount
from customers
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customers)


-- Ques3 -> which are the top 5 items with the highest average review rating?
select item_purchased , round(avg(review_rating::numeric),2) as avg_review_rating
from customers
group by 1
order by 2 desc
limit 5;

-- Ques 4 ->compare the average purchase amount between standard and express shipping?
select shipping_type , round(avg(purchase_amount),2)
from customers
where shipping_type in ('Express','Standard')
group by 1

-- Ques5 -> Do subscribed customer spend more ? compare avg spent and total revenue between subscibers and non-subscribers?

select count(customer_id) as total_customers , subscription_status , round(avg(purchase_amount),3) as avg_spent , sum(purchase_amount) as total_revenue
from customers
group by 2

-- Ques 6 -> which 5 products have the higher percentage of purchase with discount applied?
select item_purchased ,
round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end )/count(*),2) as dicounted_price
from customers
group by 1
order by 2 desc
limit 5;

-- Ques 7 ->Segment customers into new, returning and loyal based on their total number of previous purchases and show the count of each segment?

with customer_type as
(
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment 
from customers
)
select customer_segment , count(*) as number_of_customers
from customer_type
group by 1

-- Ques 8 -> what are the top 3  most purchased products within each category ?
 with items as(
 select category , item_purchased,count(customer_id) as total_orders,
 row_number() over(partition by category order by count(customer_id) desc) as item_rank
 from customers
 group by 1,2
 )
 select item_rank , category , item_purchased , total_orders
 from items
 where item_rank <=3

 -- Ques9 -> Are customers who are repeat buyers (more then 5 previous purhcase ) aslo likely to subscribe?
 
select subscription_status ,
count(customer_id) as repeat_buyers
from customers
where previous_purchases >5
group by 1

-- Ques10 -> what is the revenue contribution of each age group ?
 select age_group ,
 sum(purchase_amount) as revenue
 from customers
 group by 1
 order by 2 desc
